name: Update Anime Countdown

on:
  schedule:
    - cron: "20 * * * *"  # This runs the workflow at the start of every hour

jobs:
  update-countdown:
    runs-on: ubuntu-latest  # This specifies the runner environment (using Ubuntu here)

    steps:
      # Checkout the repository code so the workflow can access your script
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies (e.g., Python, requests)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Use the Python version you require

      # Install required Python packages (like requests)
      - name: Install dependencies
        run: |
          pip install requests

      # Run the Python script
      - name: Run the script
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}  # Use your secret webhook URL
          MESSAGE_ID: ${{ secrets.MESSAGE_ID }}    # Use your secret message ID
        run: |
          python3 update_anime_schedule.py  # Replace with your script filename if it's different
