name: Update Anime Countdown

on:
  push:
    branches:
      - main  # This triggers the workflow on pushes to the 'main' branch

jobs:
  run_script:
    runs-on: ubuntu-latest  # Runs on a fresh Ubuntu VM1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # You can specify the exact version if needed

      - name: Install dependencies
        run: |
          pip install requests pytz  # Install both requests and pytz

      - name: Run script
        run: |
          python update_anime_schedule.py  # Replace with your script filename if it's different
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}  # Fetch the secret for webhook URL
          MESSAGE_ID: ${{ secrets.MESSAGE_ID }}  # Fetch the secret for message ID
